version: '3.1'

services:
  pl4n3t:
    build: .
    image: pl4n3t:latest
    container_name: pl4n3t
    environment:
      ENVIRONMENT: development
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/src
      - ./scripts:/scripts
    # Dev user: admin pass: admin
    command: ["/scripts/wait-for-it.sh", "db:5432", "--", "/scripts/command-dev.sh"]
    ports:
      - "8000:8000"
      - "9000:9000"

  db:
    image: postgis/postgis:11-3.2
    container_name: pl4n3t-postgres
    environment: 
      POSTGRES_PASSWORD: postgres
