# Generated by Django 4.0.4 on 2024-06-27 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0014_alter_emissionresult_month'),
        ('main', '0019_alter_unitofmeasure_measure_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0031_delete_emissionssourcemonthentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la actividad')),
                ('consumption', models.FloatField(verbose_name='Uso')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1, verbose_name='Mes')),
                ('year', models.PositiveSmallIntegerField(default=2024, verbose_name='Año')),
                ('total_co2e', models.FloatField(default=0, verbose_name='Total CO₂e')),
                ('emission_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='companies.emissionssource')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='companies.location')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.unitofmeasure', verbose_name='Unidad de Medida')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ('date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ActivityGasEmittedByFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Cantidad Emitida')),
                ('co2e', models.FloatField(default=0, verbose_name='CO₂e Equivalente')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gases_emitted_by_factor', to='activities.activity')),
                ('emission_factor', models.ForeignKey(blank=True, help_text='Factor de emisión asociado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='emissions.emissionfactor')),
                ('greenhouse_gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activities.activity', verbose_name='Gas de Efecto Invernadero')),
            ],
            options={
                'verbose_name': 'Gas Emitido por Actividad y Factor',
                'verbose_name_plural': 'Gases Emitidos por Actividad y Factor',
                'ordering': ('activity', 'emission_factor', 'greenhouse_gas'),
            },
        ),
        migrations.CreateModel(
            name='ActivityGasEmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Cantidad Emitida')),
                ('co2e', models.FloatField(default=0, verbose_name='CO₂e Equivalente')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gases_emitted', to='activities.activity')),
                ('greenhouse_gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='emissions.greenhousegas', verbose_name='Gas de Efecto Invernadero')),
            ],
            options={
                'verbose_name': 'Gas Emitido por Actividad',
                'verbose_name_plural': 'Gases Emitidos por Actividad',
                'ordering': ('activity', 'greenhouse_gas'),
            },
        ),
    ]
