# Generated by Django 4.0.4 on 2024-06-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0014_alter_emissionresult_month'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitygasemittedbyfactor',
            name='greenhouse_gas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='emissions.greenhousegas', verbose_name='Gas de Efecto Invernadero'),
        ),
    ]
