# Generated by Django 4.0.4 on 2023-08-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionSourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='groups', verbose_name='Ícono')),
            ],
            options={
                'verbose_name': 'Grupo de fuente de emisión',
                'verbose_name_plural': 'Grupos de fuentes de emisión',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GHGScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=5, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Alcance GHG',
                'verbose_name_plural': 'Alcances GHG',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ISOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=5, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='emission_source_classifications.ghgscope', verbose_name='Alcance')),
            ],
            options={
                'verbose_name': 'Categoría ISO',
                'verbose_name_plural': 'Categorías ISO',
                'ordering': ('code', 'name'),
            },
        ),
    ]
