# Generated by Django 4.0.4 on 2023-08-24 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=5, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Alcance GHG',
                'verbose_name_plural': 'Alcances GHG',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='ghgscope',
            name='quantification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='emission_source_classifications.quantificationtype', verbose_name='Alcances'),
        ),
    ]
