# Generated by Django 4.0.4 on 2023-08-25 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0003_quantificationtype_ghgscope_quantification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantificationtype',
            options={'ordering': ('name',), 'verbose_name': 'Tipo de Cuantificación', 'verbose_name_plural': 'Tipos de Cuantificación'},
        ),
        migrations.AlterField(
            model_name='ghgscope',
            name='quantification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='emission_source_classifications.quantificationtype', verbose_name='Tipo de Cuantificación'),
        ),
    ]
