# Generated by Django 4.0.4 on 2023-08-25 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0004_alter_quantificationtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionsourcegroup',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='emission_source_classifications.isocategory', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
