# Generated by Django 4.0.4 on 2023-08-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_rename_factory_type_emissionfactor_factor_type'),
        ('emission_source_classifications', '0005_emissionsourcegroup_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionsourcegroup',
            name='emission_factors',
        ),
        migrations.AddField(
            model_name='emissionsourcegroup',
            name='emission_factor_type',
            field=models.ManyToManyField(blank=True, related_name='emission_source_group', to='emissions.factortype'),
        ),
    ]
