# Generated by Django 4.0.4 on 2023-08-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0006_remove_emissionsourcegroup_emission_factors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionsourcegroup',
            old_name='emission_factor_type',
            new_name='emission_factor_types',
        ),
    ]
