# Generated by Django 4.0.4 on 2023-09-27 00:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0008_emissionsourcegroup_allow_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionsourcegroup',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
