# Generated by Django 4.0.4 on 2023-09-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0009_alter_emissionsourcegroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionsourcegroup',
            name='form_name',
            field=models.CharField(blank='True', max_length=255, null=True, verbose_name='Nombre del Formulario'),
        ),
    ]
