# Generated by Django 4.0.4 on 2024-05-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0011_emissionsourcegroup_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la actividad')),
                ('normalized_name', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Nombre normalizado')),
            ],
        ),
        migrations.CreateModel(
            name='CommonEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del equipo')),
                ('normalized_name', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Nombre normalizado')),
            ],
        ),
    ]
