# Generated by Django 4.0.4 on 2024-05-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0012_commonactivity_commonequipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonactivity',
            options={'ordering': ('name',), 'verbose_name': 'Actividad Común', 'verbose_name_plural': 'Actividades Comunes'},
        ),
        migrations.AlterModelOptions(
            name='commonequipment',
            options={'ordering': ('name',), 'verbose_name': 'Maquinaría/Equipo Común', 'verbose_name_plural': 'Maquinarías/Equipos Comunes'},
        ),
    ]
