# Generated by Django 4.0.4 on 2024-05-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0013_alter_commonactivity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('normalized_name', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Nombre normalizado')),
            ],
            options={
                'verbose_name': 'Producto Común',
                'verbose_name_plural': 'Productos Comunes',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='commonactivity',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='commonequipment',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
    ]
