# Generated by Django 4.0.4 on 2024-05-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0014_commonproduct_alter_commonactivity_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('normalized_name', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Nombre normalizado')),
            ],
            options={
                'verbose_name': 'Inversion',
                'verbose_name_plural': 'Inversiones',
                'ordering': ('name',),
            },
        ),
    ]
