# Generated by Django 4.0.4 on 2024-05-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0015_investment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonactivity',
            options={'ordering': ('name',), 'verbose_name': 'Tipo de Actividad', 'verbose_name_plural': 'Tipos de Actividades'},
        ),
        migrations.AlterModelOptions(
            name='commonequipment',
            options={'ordering': ('name',), 'verbose_name': 'Tipo de Maquinaría/Equipo', 'verbose_name_plural': 'Tipos de Maquinarías/Equipos'},
        ),
        migrations.AlterModelOptions(
            name='commonproduct',
            options={'ordering': ('name',), 'verbose_name': 'Tipo de Producto', 'verbose_name_plural': 'Tipos de Productos'},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ('name',), 'verbose_name': 'Tipo de Inversion', 'verbose_name_plural': 'Tipos de Inversiones'},
        ),
    ]
