# Generated by Django 4.0.4 on 2024-05-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0016_alter_commonactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonequipment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_types', to='emission_source_classifications.emissionsourcegroup', verbose_name='Grupo'),
        ),
    ]
