# Generated by Django 4.0.4 on 2024-05-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission_source_classifications', '0017_commonequipment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonequipment',
            name='normalized_name',
            field=models.CharField(editable=False, max_length=255, verbose_name='Nombre normalizado'),
        ),
        migrations.AlterUniqueTogether(
            name='commonequipment',
            unique_together={('group', 'normalized_name')},
        ),
    ]
