# Generated by Django 4.0.4 on 2023-08-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0010_alter_webinarregistrant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Factor de Emisión',
                'verbose_name_plural': 'Factores de Emisión',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FactorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Factor de Emisión',
                'verbose_name_plural': 'Gases de Efecto Invernadero',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GreenhouseGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('acronym', models.CharField(max_length=255, verbose_name='Sigla')),
                ('kg_co2_equivalence', models.FloatField(default=1, verbose_name='Kg de CO₂ Equivalencia')),
                ('pcg_min', models.CharField(default=1, max_length=255, verbose_name='Porcentaje de calentamiento global min')),
                ('pcg_max', models.CharField(default=0, max_length=255, verbose_name='Porcentaje de calentamiento global min')),
                ('lifespan_in_years', models.CharField(max_length=255, verbose_name='Permanencia en años')),
            ],
            options={
                'verbose_name': 'Gas de Efecto Invernadero',
                'verbose_name_plural': 'Gases de Efecto Invernadero',
                'ordering': ('name', 'acronym'),
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Fuente de Emisión',
                'verbose_name_plural': 'Tipos de Fuente de Emisión',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GreenhouseGasEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Cantidad de Emisión')),
                ('bibliographic_source', models.TextField(blank=True, null=True)),
                ('percentage_uncertainty', models.FloatField(default=0, verbose_name='Porcentaje de Incertidumbre')),
                ('maximum_allowed_amount', models.FloatField(default=0, verbose_name='Cantidad Máxima Permitida')),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenhouse_emission_gases', to='emissions.emissionfactor')),
                ('greenhouse_gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenhouse_gases', to='emissions.greenhousegas', verbose_name='Gas de efecto invernadero')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.unitofmeasure', verbose_name='Unidad Factor de Emisión')),
            ],
            options={
                'verbose_name': 'Emisión de Gas de Efecto Invernadero',
                'verbose_name_plural': 'Emisiones de Gases de Efecto Invernadero',
                'ordering': ('greenhouse_gas__name',),
            },
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='factory_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='emissions.factortype', verbose_name='Tipo de Factor de Emisión'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='emissions.sourcetype', verbose_name='Tipo de Fuente de Emisión'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.unitofmeasure', verbose_name='Unidad de Consumo'),
        ),
    ]
