# Generated by Django 4.0.4 on 2023-06-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousegas',
            name='kg_co2_equivalence',
            field=models.FloatField(default=1, verbose_name='Kg de CO₂ Equivalencia'),
        ),
    ]
