# Generated by Django 4.0.4 on 2023-06-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_greenhousegas_kg_co2_equivalence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhousegas',
            name='unit',
        ),
        migrations.AddField(
            model_name='greenhousegas',
            name='pcg_max',
            field=models.CharField(default=0, max_length=255, verbose_name='Porcentaje de calentamiento global min'),
        ),
        migrations.AddField(
            model_name='greenhousegas',
            name='pcg_min',
            field=models.CharField(default=1, max_length=255, verbose_name='Porcentaje de calentamiento global min'),
        ),
    ]
