# Generated by Django 4.0.4 on 2023-08-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_alter_factortype_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionfactor',
            old_name='factory_type',
            new_name='factor_type',
        ),
    ]
