# Generated by Django 4.0.4 on 2023-06-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_remove_greenhousegas_unit_greenhousegas_pcg_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousegas',
            name='lifespan_in_years',
            field=models.CharField(default='', max_length=255, verbose_name='Permanencia en años'),
            preserve_default=False,
        ),
    ]
