# Generated by Django 4.0.4 on 2024-05-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_rename_factory_type_emissionfactor_factor_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greenhousegasemission',
            options={'ordering': ('emission_factor__source_type', 'emission_factor', 'emission_factor__source_type', 'greenhouse_gas__name'), 'verbose_name': 'Emisión de Gas de Efecto Invernadero', 'verbose_name_plural': 'Emisiones de Gases de Efecto Invernadero'},
        ),
    ]
