# Generated by Django 4.0.4 on 2023-06-08 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_unitofmeasure_name'),
        ('emissions', '0004_greenhousegas_lifespan_in_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionagent',
            name='factor',
            field=models.FloatField(default=0, verbose_name='Factor de Emisión'),
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Factor de Emisión',
                'verbose_name_plural': 'Factores de Emisión',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='emissionagent',
            name='emission_factor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emissions.emissionfactor'),
            preserve_default=False,
        ),
    ]
