# Generated by Django 4.0.4 on 2024-05-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_alter_greenhousegasemission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='measure_type',
            field=models.CharField(choices=[('UNKNOWN', 'Desconocido'), ('QUANTITY', 'Cantidad'), ('AREA', 'Area'), ('LENGTH', 'Longitud'), ('ANGLE', 'Ángulo'), ('TIME', 'Tiempo'), ('VELOCITY', 'Velocidad'), ('VOLUMEN', 'Volumen'), ('SCALE', 'Escala'), ('WEIGHT', 'Peso'), ('ENERGY', 'Energía'), ('MASS', 'Masa'), ('TEMPERATURE', 'Temperatura'), ('TEMPERATURE', 'Presión'), ('POWER', 'Potencia'), ('FREQUENCY', 'Frecuencia'), ('ENERGY_CONSUMPTION', 'Consumo de energía'), ('GEI_EMISSION', 'Emisiones de gases de efecto Invernadero')], default='UNKNOWN', help_text='Tipo de medida', max_length=18, verbose_name='Tipo de Medida'),
        ),
    ]
