# Generated by Django 4.0.4 on 2024-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0005_emissionfactor_measure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Válido desde'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Válido hasta'),
        ),
    ]
