# Generated by Django 4.0.4 on 2024-05-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0006_emissionfactor_valid_from_emissionfactor_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
