# Generated by Django 4.0.4 on 2024-05-29 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0007_emissionfactor_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='application_percentage',
            field=models.FloatField(default=1, help_text='1 equivale al 100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Porcentaje de Aplicación'),
        ),
        migrations.CreateModel(
            name='EmissionFactorComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_percentage', models.FloatField(default=0, help_text='1 equivale al 100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Porcentaje de Aplicación')),
                ('component_name', models.CharField(max_length=255, verbose_name='Nombre del Componente')),
                ('component_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_of', to='emissions.emissionfactor', verbose_name='Factor de Emisión Componente')),
                ('parent_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='emissions.emissionfactor', verbose_name='Factor de Emisión Principal')),
            ],
            options={
                'verbose_name': 'Componente de Factor de Emisión',
                'verbose_name_plural': 'Componentes de Factor de Emisión',
            },
        ),
    ]
