# Generated by Django 4.0.4 on 2024-05-31 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_unitofmeasure_measure_type'),
        ('emissions', '0009_rename_parent_factor_emissionfactorcomponent_emission_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('usage', models.FloatField(verbose_name='Uso')),
                ('total_co2e', models.FloatField(default=0, verbose_name='Total CO₂e')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unitofmeasure', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Resultado de Emisión',
                'verbose_name_plural': 'Resultados de Emisión',
                'ordering': ('date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EmissionGasDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Cantidad Emitida')),
                ('co2e', models.FloatField(default=0, verbose_name='CO₂e Equivalente')),
                ('emission_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_details', to='emissions.emissionresult')),
                ('greenhouse_gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.greenhousegas', verbose_name='Gas de Efecto Invernadero')),
            ],
            options={
                'verbose_name': 'Detalle de Emisión de Gas',
                'verbose_name_plural': 'Detalles de Emisión de Gases',
                'ordering': ('emission_result', 'greenhouse_gas'),
            },
        ),
    ]
