# Generated by Django 4.0.4 on 2024-05-31 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0028_emissionssource_product_operation_requirements_and_more'),
        ('emissions', '0010_emissionresult_emissiongasdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissiongasdetail',
            name='emission_factor',
            field=models.ForeignKey(blank=True, help_text='Factor de emisión asociado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='emissions.emissionfactor'),
        ),
        migrations.AddField(
            model_name='emissionresult',
            name='emission_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_results', to='companies.emissionssource'),
        ),
        migrations.AddField(
            model_name='emissionresult',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_results', to='companies.location'),
        ),
        migrations.AddField(
            model_name='emissionresult',
            name='month',
            field=models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='1', max_length=9, verbose_name='Mes'),
        ),
        migrations.AddField(
            model_name='emissionresult',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emissionresult',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024, verbose_name='Año'),
        ),
    ]
