# Generated by Django 4.0.4 on 2024-05-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0011_emissiongasdetail_emission_factor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissiongasdetail',
            options={'ordering': ('emission_result', 'greenhouse_gas'), 'verbose_name': 'Detalle de Emisión de Gas por Factor', 'verbose_name_plural': 'Detalles de Emisión de Gases por Factor'},
        ),
        migrations.CreateModel(
            name='TotalEmissionGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Cantidad Emitida')),
                ('co2e', models.FloatField(default=0, verbose_name='CO₂e Equivalente')),
                ('emission_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_emissions_gas', to='emissions.emissionresult')),
                ('greenhouse_gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='emissions.greenhousegas', verbose_name='Gas de Efecto Invernadero')),
            ],
            options={
                'verbose_name': 'Detalle de Emisión de Gas',
                'verbose_name_plural': 'Detalles de Emisión de Gases',
                'ordering': ('emission_result', 'greenhouse_gas'),
            },
        ),
        migrations.CreateModel(
            name='Co2ByComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2e', models.FloatField(default=0, verbose_name='CO₂e Equivalente')),
                ('emission_factor', models.ForeignKey(blank=True, help_text='Factor de emisión asociado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='emissions.emissionfactor')),
                ('emission_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co2_by_component', to='emissions.emissionresult')),
            ],
            options={
                'verbose_name': 'CO₂e por Componente',
                'verbose_name_plural': 'CO₂e por Componentes',
                'ordering': ('emission_result', 'emission_factor'),
            },
        ),
    ]
