# Generated by Django 4.0.4 on 2024-06-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0012_alter_emissiongasdetail_options_totalemissiongas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='main_component_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre del Componente Principal'),
        ),
    ]
