# Generated by Django 4.0.4 on 2024-05-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
