# Generated by Django 4.0.4 on 2024-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_companymembership_membership_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='type',
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Básica'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], default='FREE', max_length=50, verbose_name='Tipo de Membresía'),
        ),
    ]
