# Generated by Django 4.0.4 on 2024-05-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_remove_membership_type_membership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='analysis_tools',
            field=models.BooleanField(default=False, verbose_name='Herramientas de análisis y generación de informes personalizados'),
        ),
        migrations.AddField(
            model_name='membership',
            name='basic_support',
            field=models.BooleanField(default=True, verbose_name='Acceso al soporte básico a través de preguntas frecuentes o correo electrónico'),
        ),
        migrations.AddField(
            model_name='membership',
            name='custom_api_access',
            field=models.BooleanField(default=False, verbose_name='Acceso a una API personalizada para desarrollar integraciones personalizadas'),
        ),
        migrations.AddField(
            model_name='membership',
            name='dedicated_support',
            field=models.BooleanField(default=False, verbose_name='Un representante de soporte asignado exclusivamente a la cuenta'),
        ),
        migrations.AddField(
            model_name='membership',
            name='emission_sources',
            field=models.BooleanField(default=True, verbose_name='Registro de todas las Fuentes de emisión'),
        ),
        migrations.AddField(
            model_name='membership',
            name='footprint_types',
            field=models.CharField(default='Huella de Carbono', max_length=255, verbose_name='Tipos de huella'),
        ),
        migrations.AddField(
            model_name='membership',
            name='general_support',
            field=models.BooleanField(default=True, verbose_name='Soporte técnico General'),
        ),
        migrations.AddField(
            model_name='membership',
            name='liquidation_options',
            field=models.CharField(default='Anual', max_length=255, verbose_name='Liquidación: Mensual, Trimestral, Anual'),
        ),
        migrations.AddField(
            model_name='membership',
            name='num_brands',
            field=models.IntegerField(default=1, verbose_name='Número de Marcas'),
        ),
        migrations.AddField(
            model_name='membership',
            name='num_locations',
            field=models.IntegerField(default=1, verbose_name='Número de Sedes'),
        ),
        migrations.AddField(
            model_name='membership',
            name='num_users',
            field=models.IntegerField(default=1, verbose_name='Usuarios por organización'),
        ),
        migrations.AddField(
            model_name='membership',
            name='storage_capacity',
            field=models.CharField(default='No sube soportes', max_length=255, verbose_name='Mayor capacidad de almacenamiento para archivos y datos'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tutorials',
            field=models.BooleanField(default=True, verbose_name='Tutoriales'),
        ),
        migrations.AddField(
            model_name='membership',
            name='webinars',
            field=models.BooleanField(default=False, verbose_name='Webinars, documentación especializada, etc.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.IntegerField(default=365, verbose_name='Duración en días'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('FREE', 'Gratuito'), ('BASIC', 'Básica'), ('PREMIUM', 'Premium'), ('ELITE', 'Elite')], default='FREE', max_length=50, verbose_name='Tipo de Membresía'),
        ),
    ]
