# Generated by Django 4.0.4 on 2024-05-17 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_companymembership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='proposed_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='proposed_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_membership', to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('AWAITING_PAYMENT', 'Awaiting Payment')], default='PENDING', max_length=16),
        ),
    ]
