# Generated by Django 4.0.4 on 2024-05-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_companymembership_proposed_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_default',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
