# Generated by Django 4.0.4 on 2023-06-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_unitofmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(blank=True, help_text='El(los) nombre(s) de una unidad de medida (udm) particular. Los ejemplos incluirían lo siguiente:1) para el área udm - metros cuadrados <br />2) para udm Time - segundos <br />3) para el área udm - metros <br />4) Ángulo udm - grados.', max_length=256, verbose_name='Nombre'),
        ),
    ]
