# Generated by Django 4.0.4 on 2023-06-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_unitofmeasure_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Sector')),
            ],
            options={
                'verbose_name': 'Sector Económico',
                'verbose_name_plural': 'Sectores Económicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tipo de Industria')),
            ],
            options={
                'verbose_name': 'Tipo de Industria',
                'verbose_name_plural': 'Tipos de Industria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tipo de sede')),
            ],
            options={
                'verbose_name': 'Tipo de sede',
                'verbose_name_plural': 'Tipos de sede',
                'ordering': ['name'],
            },
        ),
    ]
