# Generated by Django 4.0.4 on 2023-06-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_economicsector_industrytype_locationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='measure_type',
            field=models.CharField(choices=[('', 'Desconocido'), ('AREA', 'Area'), ('LENGTH', 'Longitud'), ('ANGLE', 'Ángulo'), ('TIME', 'Tiempo'), ('VELOCITY', 'Velocidad'), ('VOLUMEN', 'Volumen'), ('SCALE', 'Escala'), ('WEIGHT', 'Peso'), ('ENERGY', 'Energía'), ('MASS', 'Masa'), ('TEMPERATURE', 'Temperatura'), ('TEMPERATURE', 'Presión'), ('POWER', 'Potencia'), ('FREQUENCY', 'Frecuencia'), ('ENERGY_CONSUMPTION', 'Consumo de energía')], help_text='Tipo de medida', max_length=18, verbose_name='Tipo de Medida'),
        ),
    ]
