# Generated by Django 4.0.4 on 2023-06-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_unitofmeasure_name_standard_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['measure_type', 'name'], 'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
    ]
