# Generated by Django 4.0.4 on 2023-07-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_unitofmeasure_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarRegistrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
