# Generated by Django 4.0.4 on 2023-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_webinarregistrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarregistrant',
            name='company_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
