# Generated by Django 4.0.4 on 2023-07-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_webinarregistrant_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarregistrant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
