# Generated by Django 4.0.4 on 2023-10-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_alter_emissionssource_vehicle_efficiency_and_more'),
        ('main', '0013_alter_configuration_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
