# Generated by Django 4.0.4 on 2024-05-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_configuration_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
