# Generated by Django 4.0.4 on 2024-05-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_unitofmeasure_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='is_gei_unit',
            field=models.BooleanField(default=False),
        ),
    ]
