# Generated by Django 4.0.4 on 2024-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_unitofmeasure_is_gei_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='is_gei_unit',
            field=models.BooleanField(default=False, verbose_name='Es una unidad de medida GEI'),
        ),
    ]
