# Generated by Django 4.0.4 on 2024-05-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_unitofmeasure_is_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='symbol',
            field=models.CharField(help_text='El símbolo utilizado para esta unidad de medida, como "ft" para pies o "m" para metro.', max_length=32, verbose_name='Símbolo'),
        ),
    ]
