# Generated by Django 4.0.4 on 2023-12-19 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('version', models.FloatField(blank=True, default=1.0)),
                ('period', models.CharField(max_length=10)),
                ('introduction', models.TextField(blank=True)),
                ('quantification_methodology', models.TextField(blank=True)),
                ('emissions_inventory_exclusions', models.TextField(blank=True)),
                ('report_results', models.TextField(blank=True)),
                ('emissions_inventory', models.TextField(blank=True)),
                ('emissions_consolidation', models.TextField(blank=True)),
                ('annexes', models.TextField(blank=True)),
                ('definitions', models.TextField(blank=True)),
                ('company_description', models.TextField(blank=True)),
                ('baseline_year_diagnostic', models.TextField(blank=True)),
                ('intended_use', models.TextField(blank=True)),
                ('carbon_footprint_determination', models.TextField(blank=True)),
                ('emissions_consolidation_year', models.TextField(blank=True)),
                ('carbon_footprint_quantification', models.TextField(blank=True)),
                ('emissions_reduction_recommendations', models.TextField(blank=True)),
                ('organizational_description', models.TextField(blank=True)),
                ('diagnostic_scope', models.TextField(blank=True)),
                ('diagnostic_objectives', models.TextField(blank=True)),
                ('gei_inventory_boundaries', models.TextField(blank=True)),
                ('conclusions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('period', models.CharField(max_length=10)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='generated_reports/')),
                ('is_finalized', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate')),
            ],
        ),
    ]
