# Generated by Django 4.0.4 on 2023-12-19 15:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reporttemplate_annexes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='fields_ordered',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Secciones del Reporte'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='report_frequency',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Frecuencia del Informe'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='annexes',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anexos'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='baseline_year_diagnostic',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Año base diagnostico e informe'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='carbon_footprint_determination',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Determinación de la Huella de Carbono'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='carbon_footprint_quantification',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Cuantificación huella de carbono'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='company_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción de la Empresa'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='conclusions',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Conclusiones'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='definitions',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Definiciones'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='diagnostic_objectives',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Objetivos del Diagnostico e Informe'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='diagnostic_scope',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Alcance del diagnostico'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='emissions_consolidation',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Consolidado del inventario de emisiones de gei generadas Año/periodo'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='emissions_consolidation_year',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Consolidado gei emitidas durante el año'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='emissions_inventory',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Inventario de cuantificacion de emisiones gei organizacionales'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='emissions_inventory_exclusions',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Exclusiones del inventario de las fuentes de Emisión'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='emissions_reduction_recommendations',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Recomendaciones en reducciones de emisiones de GEI'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='gei_inventory_boundaries',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Limites del inventario de GEI'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='intended_use',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Uso previsto y usuarios y usuarios previstos del informe'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='introduction',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='organizational_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción Organizacional que realiza el diagnostico'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='period',
            field=models.CharField(max_length=64, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='quantification_methodology',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Metodología de Cuantificación'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_results',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Resultados del informe'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='version',
            field=models.FloatField(blank=True, default=1.0, verbose_name='Versión'),
        ),
    ]
