# Generated by Django 4.0.4 on 2024-05-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_reporttemplate_period_reporttemplate_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
    ]
