# Generated by Django 4.0.4 on 2024-05-23 20:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('companies', '0028_emissionssource_product_operation_requirements_and_more'),
        ('reports', '0005_remove_reporttemplate_tags_delete_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('version', models.FloatField(blank=True, default=1.0, verbose_name='Versión')),
                ('introduction', ckeditor.fields.RichTextField(blank=True, verbose_name='Introducción')),
                ('definitions', ckeditor.fields.RichTextField(blank=True, verbose_name='Definiciones')),
                ('company_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción de la Empresa')),
                ('organizational_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción Organizacional que realiza el diagnostico')),
                ('baseline_year_diagnostic', ckeditor.fields.RichTextField(blank=True, verbose_name='Año base diagnostico e informe')),
                ('report_frequency', ckeditor.fields.RichTextField(blank=True, verbose_name='Frecuencia del Informe')),
                ('intended_use', ckeditor.fields.RichTextField(blank=True, verbose_name='Uso previsto y usuarios y usuarios previstos del informe')),
                ('diagnostic_scope', ckeditor.fields.RichTextField(blank=True, verbose_name='Alcance del diagnostico')),
                ('diagnostic_objectives', ckeditor.fields.RichTextField(blank=True, verbose_name='Objetivos del Diagnostico e Informe')),
                ('quantification_methodology', ckeditor.fields.RichTextField(blank=True, verbose_name='Metodología de Cuantificación')),
                ('emissions_inventory_exclusions', ckeditor.fields.RichTextField(blank=True, verbose_name='Exclusiones del inventario de las fuentes de Emisión')),
                ('carbon_footprint_determination', ckeditor.fields.RichTextField(blank=True, verbose_name='Determinación de la Huella de Carbono')),
                ('gei_inventory_boundaries', ckeditor.fields.RichTextField(blank=True, verbose_name='Limites del inventario de GEI')),
                ('report_results', ckeditor.fields.RichTextField(blank=True, verbose_name='Resultados del informe')),
                ('emissions_inventory', ckeditor.fields.RichTextField(blank=True, verbose_name='Inventario de Cuantificación de emisiones gei organizacionales')),
                ('emissions_consolidation', ckeditor.fields.RichTextField(blank=True, verbose_name='Consolidado del inventario de emisiones de gei generadas Año/periodo')),
                ('emissions_consolidation_year', ckeditor.fields.RichTextField(blank=True, verbose_name='Consolidado gei emitidas durante el año')),
                ('carbon_footprint_quantification', ckeditor.fields.RichTextField(blank=True, verbose_name='Cuantificación huella de carbono')),
                ('emissions_reduction_recommendations', ckeditor.fields.RichTextField(blank=True, verbose_name='Recomendaciones en reducciones de emisiones de GEI')),
                ('conclusions', ckeditor.fields.RichTextField(blank=True, verbose_name='Conclusiones')),
                ('annexes', ckeditor.fields.RichTextField(blank=True, verbose_name='Anexos')),
                ('fields_ordered', models.CharField(blank=True, max_length=1024, verbose_name='Secciones del Reporte')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('version', models.FloatField(blank=True, default=1.0, verbose_name='Versión')),
                ('introduction', ckeditor.fields.RichTextField(blank=True, verbose_name='Introducción')),
                ('definitions', ckeditor.fields.RichTextField(blank=True, verbose_name='Definiciones')),
                ('company_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción de la Empresa')),
                ('organizational_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción Organizacional que realiza el diagnostico')),
                ('baseline_year_diagnostic', ckeditor.fields.RichTextField(blank=True, verbose_name='Año base diagnostico e informe')),
                ('report_frequency', ckeditor.fields.RichTextField(blank=True, verbose_name='Frecuencia del Informe')),
                ('intended_use', ckeditor.fields.RichTextField(blank=True, verbose_name='Uso previsto y usuarios y usuarios previstos del informe')),
                ('diagnostic_scope', ckeditor.fields.RichTextField(blank=True, verbose_name='Alcance del diagnostico')),
                ('diagnostic_objectives', ckeditor.fields.RichTextField(blank=True, verbose_name='Objetivos del Diagnostico e Informe')),
                ('quantification_methodology', ckeditor.fields.RichTextField(blank=True, verbose_name='Metodología de Cuantificación')),
                ('emissions_inventory_exclusions', ckeditor.fields.RichTextField(blank=True, verbose_name='Exclusiones del inventario de las fuentes de Emisión')),
                ('carbon_footprint_determination', ckeditor.fields.RichTextField(blank=True, verbose_name='Determinación de la Huella de Carbono')),
                ('gei_inventory_boundaries', ckeditor.fields.RichTextField(blank=True, verbose_name='Limites del inventario de GEI')),
                ('report_results', ckeditor.fields.RichTextField(blank=True, verbose_name='Resultados del informe')),
                ('emissions_inventory', ckeditor.fields.RichTextField(blank=True, verbose_name='Inventario de Cuantificación de emisiones gei organizacionales')),
                ('emissions_consolidation', ckeditor.fields.RichTextField(blank=True, verbose_name='Consolidado del inventario de emisiones de gei generadas Año/periodo')),
                ('emissions_consolidation_year', ckeditor.fields.RichTextField(blank=True, verbose_name='Consolidado gei emitidas durante el año')),
                ('carbon_footprint_quantification', ckeditor.fields.RichTextField(blank=True, verbose_name='Cuantificación huella de carbono')),
                ('emissions_reduction_recommendations', ckeditor.fields.RichTextField(blank=True, verbose_name='Recomendaciones en reducciones de emisiones de GEI')),
                ('conclusions', ckeditor.fields.RichTextField(blank=True, verbose_name='Conclusiones')),
                ('annexes', ckeditor.fields.RichTextField(blank=True, verbose_name='Anexos')),
                ('fields_ordered', models.CharField(blank=True, max_length=1024, verbose_name='Secciones del Reporte')),
                ('period', models.CharField(max_length=10)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='generated_reports/')),
                ('is_finalized', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('version', models.FloatField(blank=True, default=1.0, verbose_name='Versión')),
                ('introduction', ckeditor.fields.RichTextField(blank=True, verbose_name='Introducción')),
                ('definitions', ckeditor.fields.RichTextField(blank=True, verbose_name='Definiciones')),
                ('company_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción de la Empresa')),
                ('organizational_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción Organizacional que realiza el diagnostico')),
                ('baseline_year_diagnostic', ckeditor.fields.RichTextField(blank=True, verbose_name='Año base diagnostico e informe')),
                ('report_frequency', ckeditor.fields.RichTextField(blank=True, verbose_name='Frecuencia del Informe')),
                ('intended_use', ckeditor.fields.RichTextField(blank=True, verbose_name='Uso previsto y usuarios y usuarios previstos del informe')),
                ('diagnostic_scope', ckeditor.fields.RichTextField(blank=True, verbose_name='Alcance del diagnostico')),
                ('diagnostic_objectives', ckeditor.fields.RichTextField(blank=True, verbose_name='Objetivos del Diagnostico e Informe')),
                ('quantification_methodology', ckeditor.fields.RichTextField(blank=True, verbose_name='Metodología de Cuantificación')),
                ('emissions_inventory_exclusions', ckeditor.fields.RichTextField(blank=True, verbose_name='Exclusiones del inventario de las fuentes de Emisión')),
                ('carbon_footprint_determination', ckeditor.fields.RichTextField(blank=True, verbose_name='Determinación de la Huella de Carbono')),
                ('gei_inventory_boundaries', ckeditor.fields.RichTextField(blank=True, verbose_name='Limites del inventario de GEI')),
                ('report_results', ckeditor.fields.RichTextField(blank=True, verbose_name='Resultados del informe')),
                ('emissions_inventory', ckeditor.fields.RichTextField(blank=True, verbose_name='Inventario de Cuantificación de emisiones gei organizacionales')),
                ('emissions_consolidation', ckeditor.fields.RichTextField(blank=True, verbose_name='Consolidado del inventario de emisiones de gei generadas Año/periodo')),
                ('emissions_consolidation_year', ckeditor.fields.RichTextField(blank=True, verbose_name='Consolidado gei emitidas durante el año')),
                ('carbon_footprint_quantification', ckeditor.fields.RichTextField(blank=True, verbose_name='Cuantificación huella de carbono')),
                ('emissions_reduction_recommendations', ckeditor.fields.RichTextField(blank=True, verbose_name='Recomendaciones en reducciones de emisiones de GEI')),
                ('conclusions', ckeditor.fields.RichTextField(blank=True, verbose_name='Conclusiones')),
                ('annexes', ckeditor.fields.RichTextField(blank=True, verbose_name='Anexos')),
                ('fields_ordered', models.CharField(blank=True, max_length=1024, verbose_name='Secciones del Reporte')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
