# Generated by Django 4.0.4 on 2024-05-23 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_emissionssource_product_operation_requirements_and_more'),
        ('reports', '0007_alter_companytemplate_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytemplate',
            options={'verbose_name': 'Plantilla de Compañía', 'verbose_name_plural': 'Plantillas de Compañía'},
        ),
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'verbose_name': 'Plantilla de Pl4n3t', 'verbose_name_plural': 'Plantillas de Pl4n3t'},
        ),
        migrations.AddField(
            model_name='report',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
