# Generated by Django 4.0.4 on 2023-10-04 17:50

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import documents.models
import main.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('trashed', models.BooleanField(db_index=True, default=False)),
                ('object_pk', models.CharField(db_index=True, max_length=64, verbose_name='object ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/src/media'), upload_to=documents.models.upload_location)),
                ('thumbnails', models.FileField(blank=True, max_length=300, null=True, storage=django.core.files.storage.FileSystemStorage(location='/src/media'), upload_to=documents.models.upload_location)),
                ('file_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de archivo')),
                ('size', models.BigIntegerField(default=0, verbose_name='Tamaño')),
                ('is_multimedia', models.BooleanField(default=False, verbose_name='Es un Archivo Multimedia')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, help_text='Una Lista separada por comas', max_length=200, null=True)),
                ('status', models.CharField(choices=[('WAITING_REVISE', 'Esperando Revisión'), ('WAITING_UPDATE', 'Esperando Actualización'), ('APPROVAL', 'Aprobado'), ('EXPIRED', 'Expirado'), ('REJECTED', 'Rechazado')], default='WAITING_REVISE', max_length=20, verbose_name='Estado')),
                ('content_type', models.ForeignKey(limit_choices_to=main.base.limit_content_type_choices, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_%(class)s', to='contenttypes.contenttype', verbose_name='content type')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
