# Generated by Django 4.0.4 on 2023-08-17 17:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0010_alter_webinarregistrant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Industria')),
                ('size', models.CharField(choices=[('SMALL', 'Pequeña (1-50 empleados)'), ('MEDIUM', 'Mediana (51-200 empleados)'), ('LARGE', 'Grande (201+ empleados)')], default='SMALL', max_length=10, verbose_name='Tamaño de la Empresa')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Página Web')),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Posición geográfica')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Usuario de Compañía',
                'verbose_name_plural': 'Usuarios de las Compañías',
                'ordering': ('company', 'user'),
            },
        ),
        migrations.CreateModel(
            name='EmissionsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=255, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='emission_sources/', verbose_name='Imagen')),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Fuente de Emisión',
                'verbose_name_plural': 'Fuentes de Emisión',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('country', models.CharField(max_length=255, verbose_name='Pais')),
                ('zip_code', models.CharField(max_length=255, verbose_name='Código Postal')),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Posición Geográfica')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.company')),
                ('location_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.locationtype', verbose_name='Tipo de Sede')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ('company__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EmissionsSourceMonthEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField()),
                ('month', models.CharField(choices=[('January', 'Enero'), ('February', 'Febrero'), ('March', 'Marzo'), ('April', 'Abril'), ('May', 'Mayo'), ('June', 'Junio'), ('July', 'Julio'), ('August', 'Agosto'), ('September', 'Septiembre'), ('October', 'Octubre'), ('November', 'Noviembre'), ('December', 'Diciembre')], max_length=9)),
                ('emission', models.FloatField(default=0.0)),
                ('emission_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.emissionssource')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Registro Mensual de Emisión',
                'verbose_name_plural': 'Registro Mensual de Emisiones',
                'ordering': ('register_date', 'month'),
            },
        ),
    ]
