# Generated by Django 4.0.4 on 2023-06-08 21:46

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Industria')),
                ('size', models.CharField(choices=[('SMALL', 'Pequeña (1-50 empleados)'), ('MEDIUM', 'Mediana (51-200 empleados)'), ('LARGE', 'Grande (201+ empleados)')], default='SMALL', max_length=10, verbose_name='Tamaño de la Empresa')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Página Web')),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Posición geográfica')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('country', models.CharField(max_length=255, verbose_name='Pais')),
                ('zip_code', models.CharField(max_length=255, verbose_name='Código Postal')),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Posición Geográfica')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.company')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ('company__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LocationEmissionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('emission_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='emissions.emissionagent')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='companies.location')),
            ],
            options={
                'verbose_name': 'Agente emisor de una sede',
                'verbose_name_plural': 'Agentes emisores por sede',
                'ordering': ('emission_agent__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EmissionAgentMonthEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField()),
                ('month', models.CharField(choices=[('January', 'Enero'), ('February', 'Febrero'), ('March', 'Marzo'), ('April', 'Abril'), ('May', 'Mayo'), ('June', 'Junio'), ('July', 'Julio'), ('August', 'Agosto'), ('September', 'Septiembre'), ('October', 'Octubre'), ('November', 'Noviembre'), ('December', 'Diciembre')], max_length=9)),
                ('emission', models.FloatField(default=0.0)),
                ('emission_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.locationemissionagent')),
            ],
            options={
                'verbose_name': 'Registro Mensual de Emisión',
                'verbose_name_plural': 'Registro Mensual de Emisiones',
                'ordering': ('register_date', 'month'),
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
                'ordering': ('company', 'user'),
            },
        ),
    ]
