# Generated by Django 4.0.4 on 2023-08-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('emission_source_classifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionssource',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_sources', to='emission_source_classifications.emissionsourcegroup'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_source_locations', to='companies.location'),
        ),
    ]
