# Generated by Django 4.0.4 on 2023-06-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={'ordering': ('company', 'user'), 'verbose_name': 'Usuario de Compañía', 'verbose_name_plural': 'Usuarios de las Compañías'},
        ),
    ]
