# Generated by Django 4.0.4 on 2023-06-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_unitofmeasure'),
        ('companies', '0002_alter_companyuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionagentmonthentry',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.unitofmeasure'),
            preserve_default=False,
        ),
    ]
