# Generated by Django 4.0.4 on 2023-08-17 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0010_alter_webinarregistrant_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emissions', '0001_initial'),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionssource',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_sources', to='emissions.sourcetype', verbose_name='Tipo de Fuente de Emisión'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='economic_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.economicsector', verbose_name='Sector Económico'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.industrytype', verbose_name='Tipo de Industria'),
        ),
    ]
