# Generated by Django 4.0.4 on 2023-06-09 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_economicsector_industrytype_locationtype'),
        ('companies', '0003_emissionagentmonthentry_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='economic_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.economicsector', verbose_name='Sector Económico'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.industrytype', verbose_name='Tipo de Industria'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.locationtype', verbose_name='Tipo de Sede'),
        ),
    ]
