# Generated by Django 4.0.4 on 2023-08-27 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_brand_location_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador de empresa'), ('MANAGER', 'Gerente de sede'), ('EMPLOYEE', 'Empleado')], default='EMPLOYEE', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
