# Generated by Django 4.0.4 on 2023-08-27 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0006_company_ciiu_code_company_country_company_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador de empresa'), ('MANAGER', 'Gerente de sede'), ('EMPLOYEE', 'Empleado')], default='EMPLOYEE', max_length=20, verbose_name='Rol')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Compañía',
                'verbose_name_plural': 'Usuarios de las Compañías',
                'ordering': ('company', 'user'),
            },
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
    ]
