# Generated by Django 4.0.4 on 2023-08-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_location_state_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
