# Generated by Django 4.0.4 on 2023-08-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_location_email_location_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='employees',
            field=models.IntegerField(default=0, verbose_name='Empleados'),
        ),
    ]
