# Generated by Django 4.0.4 on 2023-08-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_rename_factory_type_emissionfactor_factor_type'),
        ('companies', '0014_emissionssource_emission_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionssource',
            name='emission_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_sources', to='emissions.emissionfactor', verbose_name='Factor de Emisión'),
        ),
    ]
