# Generated by Django 4.0.4 on 2023-09-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_emissionssource_vehicle_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionssource',
            name='vehicle_efficiency',
            field=models.FloatField(default=0, verbose_name='Eficiencia del Vehículo'),
        ),
        migrations.AlterField(
            model_name='emissionssource',
            name='vehicle_efficiency_unit',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Unidad de Medida'),
        ),
    ]
