# Generated by Django 4.0.4 on 2023-10-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_alter_emissionssource_vehicle_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionssource',
            name='electricity_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='Eficiencia Energética'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='electricity_efficiency_unit',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Unidad Eficiencia Energética'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='electricity_source',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Fuente de generación'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='electricity_supplier',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Proveedor de Electricidad'),
        ),
    ]
