# Generated by Django 4.0.4 on 2024-05-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_alter_emissionssource_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionssource',
            name='activity_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Actividad'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Equipo'),
        ),
    ]
