# Generated by Django 4.0.4 on 2024-05-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_emissionssource_activity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionssource',
            name='acquired_service',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Servicio Adquirido'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='energy_efficiency_unit',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='energy_efficiency_value',
            field=models.FloatField(default=0, verbose_name='Eficiencia energética del equipo o sistema que usa combustible'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='exist_steam_specific_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='final_disposal_of_refrigerants',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='disposición final de refrigerantes'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='fuel_management',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Gestión del Combustible'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='fuel_store',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Almacenamiento del Combustible'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='ghg_emission_are_recorded',
            field=models.BooleanField(default=False, verbose_name='Se registran y monitorean las emisiones GEI'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='good_and_service_acquired_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tipo de Bien o Servicio Adquirido'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='has_refrigerant_conversions',
            field=models.BooleanField(default=False, verbose_name='¿Se han realizado conversiones a refrigerantes con menor potencial de calentamiento global (PCG)?'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='has_refrigerant_leaks',
            field=models.BooleanField(default=False, verbose_name='¿Existen Fugas del refrigerante en el equipo?'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='investment_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tipo de Inversión'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='know_type_electricity_generation_source',
            field=models.BooleanField(default=False, verbose_name='Conoce el tipo de fuente de generación de electricidad'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='leased_assets_duration_unit',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Unidad de Medida de la duración'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='leased_assets_durations',
            field=models.IntegerField(default=0, verbose_name='Duración del contrato de Arrendamiento'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='leased_assets_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tipo de bien arrendado'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='origen'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Producto'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='refrigerant_capacity',
            field=models.FloatField(default=0, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='refrigerant_capacity_unit',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='service_life',
            field=models.IntegerField(default=0, verbose_name='Vida Útil'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='service_life_unit',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Unidad de Medida Vida útil'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Proveedor'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='support_actions_refrigerant_equipment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='acciones realiza para el mantenimiento y reparaciones del equipo'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='waste_classification',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Clase de desperdicio'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='waste_type',
            field=models.CharField(blank=True, choices=[('food', 'Residuos de alimentos'), ('gardening', 'Residuos de jardinería'), ('kitchen', 'Residuos de cocina'), ('animals', 'Residuos de animales'), ('other', 'Otro')], max_length=128, null=True, verbose_name='Tipo de desperdicio'),
        ),
    ]
