# Generated by Django 4.0.4 on 2024-05-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_alter_emissionssource_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionssource',
            name='waste_management',
            field=models.TextField(blank=True, null=True, verbose_name='Manejo de desperdicio'),
        ),
    ]
