# Generated by Django 4.0.4 on 2024-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_emissionssource_waste_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionssource',
            name='waste_management_data',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
