# Generated by Django 4.0.4 on 2024-05-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_emissionssource_waste_management_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionssource',
            name='final_disposal_of_refrigerants',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='disposición final de refrigerantes'),
        ),
        migrations.AlterField(
            model_name='emissionssource',
            name='support_actions_refrigerant_equipment',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='acciones realiza para el mantenimiento y reparaciones del equipo'),
        ),
    ]
