# Generated by Django 4.0.4 on 2024-05-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_alter_emissionssource_final_disposal_of_refrigerants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionssource',
            name='product_operation_requirements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Requerimientos para el funcionamiento del Producto'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='units_sold',
            field=models.IntegerField(default=0, verbose_name='Unidades vendidas'),
        ),
        migrations.AddField(
            model_name='emissionssource',
            name='units_sold_period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Periodo de Ventas'),
        ),
    ]
