# Generated by Django 4.0.4 on 2024-06-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_member_email_member_status_alter_member_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('company', 'email')},
        ),
    ]
