# Generated by Django 4.0.4 on 2024-06-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_alter_member_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmissionsSourceMonthEntry',
        ),
    ]
